apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-and-push-run
spec:
  serviceAccountName: quayaccount
  taskRef:
    name: buildah
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/chetan-rns/backend
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: quay.io/cbanavik/test:latest
